### ISSUE TITLE
Error when running cypress after update

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#4460]
After upgrading cypress to 3.4.1, we have the following error both locally and on Jenkins when we run the regression tests using the shell script:

> [1m[47m[31mA JavaScript error occurred in the main process
[30mUncaught Exception:
TypeError: strToArray(...).map is not a function
    at Object.toObject (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/util/args.js:215:39)
    at Object.start (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/cypress.js:84:40)
    at Object.<anonymous> (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/index.js:26:43)
    at Object.<anonymous> (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/index.js:28:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/app/index.js:2:1)
    at Object.<anonymous> (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/app/index.js:3:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/data/jenkins/.cache/Cypress/3.4.1/Cypress/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3[0m
[34mℹ[39m [90m｢wdm｣[39m: Compiling...
/tmp/jenkins6693297835598800501.sh: line 7: 13760 Terminated              ./ci-scripts/e2e-cypress.sh regression

On mac, it tries to open the electron app instead of running headless
